use crate::cleaner::traits::{CleanTargetItem, Cleaner};
use crate::safety::allowlist::CleanCategory;
use crate::utils::fs::{calculate_size, expand_tilde};
use crate::utils::platform::is_process_running;
use anyhow::{bail, Result};
use std::fs;

pub struct XcodeDerivedDataCleaner;

impl Cleaner for XcodeDerivedDataCleaner {
    fn name(&self) -> &'static str {
        "Xcode DerivedData"
    }

    fn category(&self) -> CleanCategory {
        CleanCategory::XcodeDerivedData
    }

    fn description(&self) -> &'static str {
        "Build artifacts and indexes generated by Xcode in ~/Library/Developer/Xcode/DerivedData"
    }

    fn scan(&self) -> Result<Vec<CleanTargetItem>> {
        if is_process_running("Xcode") {
            bail!("Xcode is currently running. Please quit Xcode before scanning or cleaning DerivedData.");
        }

        let dir = expand_tilde("~/Library/Developer/Xcode/DerivedData");
        let mut items = Vec::new();

        if dir.is_dir() {
            for entry in fs::read_dir(&dir)? {
                if let Ok(entry) = entry {
                    let path = entry.path();
                    if let Ok((size, count)) = calculate_size(&path) {
                        if size > 0 {
                            let name = entry.file_name().to_string_lossy().to_string();
                            items.push(CleanTargetItem {
                                path,
                                size_bytes: size,
                                file_count: count,
                                description: format!("Xcode DerivedData for {}", name),
                            });
                        }
                    }
                }
            }
        }

        items.sort_by(|a, b| b.size_bytes.cmp(&a.size_bytes));
        Ok(items)
    }
}

pub struct XcodeArchivesCleaner;

impl Cleaner for XcodeArchivesCleaner {
    fn name(&self) -> &'static str {
        "Xcode Archives"
    }

    fn category(&self) -> CleanCategory {
        CleanCategory::XcodeArchives
    }

    fn description(&self) -> &'static str {
        "Old build archives stored in ~/Library/Developer/Xcode/Archives"
    }

    fn scan(&self) -> Result<Vec<CleanTargetItem>> {
        let dir = expand_tilde("~/Library/Developer/Xcode/Archives");
        let mut items = Vec::new();

        if dir.is_dir() {
            for entry in fs::read_dir(&dir)? {
                if let Ok(entry) = entry {
                    let path = entry.path();
                    if let Ok((size, count)) = calculate_size(&path) {
                        if size > 0 {
                            let name = entry.file_name().to_string_lossy().to_string();
                            items.push(CleanTargetItem {
                                path,
                                size_bytes: size,
                                file_count: count,
                                description: format!("Xcode Archive {}", name),
                            });
                        }
                    }
                }
            }
        }

        items.sort_by(|a, b| b.size_bytes.cmp(&a.size_bytes));
        Ok(items)
    }
}

pub struct XcodeDeviceSupportCleaner;

impl Cleaner for XcodeDeviceSupportCleaner {
    fn name(&self) -> &'static str {
        "Xcode iOS DeviceSupport"
    }

    fn category(&self) -> CleanCategory {
        CleanCategory::XcodeDeviceSupport
    }

    fn description(&self) -> &'static str {
        "Symbols and device support files for old iOS versions in ~/Library/Developer/Xcode/iOS DeviceSupport"
    }

    fn scan(&self) -> Result<Vec<CleanTargetItem>> {
        let dir = expand_tilde("~/Library/Developer/Xcode/iOS DeviceSupport");
        let mut items = Vec::new();

        if dir.is_dir() {
            for entry in fs::read_dir(&dir)? {
                if let Ok(entry) = entry {
                    let path = entry.path();
                    if let Ok((size, count)) = calculate_size(&path) {
                        if size > 0 {
                            let name = entry.file_name().to_string_lossy().to_string();
                            items.push(CleanTargetItem {
                                path,
                                size_bytes: size,
                                file_count: count,
                                description: format!("iOS DeviceSupport for {}", name),
                            });
                        }
                    }
                }
            }
        }

        items.sort_by(|a, b| b.size_bytes.cmp(&a.size_bytes));
        Ok(items)
    }
}
